import { Inter } from "next/font/google";
import "./globals.css";
import { ProjectProvider } from '../context/ProjectContext';
import Tag from './components/Tag'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProjectProvider>
          {children}
          <Tag />
        </ProjectProvider>
      </body>
    </html>
  );
}
